
services:
  app:
    image: 'sha256:672cf48bccfcc039504689907fb023dbafa5500999f23a26a269720d08928edf'
    expose:
      - '8080'
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_PASSWORD=admin
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin